pub const CLIENT_IDENTIFICATION: &str = "CLIENT_IDENTIFICATION";

pub const CLIENT_IDENTIFICATION_RESPONSE: &str = "CLIENT_IDENTIFICATION_RESPONSE";
pub const CLIENT_IDENTIFICATION_PUSH: &str = "CLIENT_IDENTIFICATION_PUSH";
pub const CLIENT_IDENTIFICATION_REQUEST: &str = "CLIENT_IDENTIFICATION_REQUEST";
pub const CLIENT_IDENTIFICATION_CLOSE: &str = "CLIENT_IDENTIFICATION_CLOSE";
pub const CLIENT_IDENTIFICATION_ERROR: &str = "CLIENT_IDENTIFICATION_ERROR";
pub const CLIENT_IDENTIFICATION_CONNECT_ERROR: &str = "CLIENT_IDENTIFICATION_CONNECT_ERROR";

